# queue:
#   name: Hosted VS2017
#   condition: succeeded()

steps:
- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.7.0
  inputs:
    versionSpec: 4.7.0

# - task: DotNetCoreCLI@2
#   displayName: Build
#   inputs:
#     projects: '/src/API/API.csproj'
#     arguments: '--configuration $(BuildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: Test
#   inputs:
#     command: test
#     publishTestResults: true
#     arguments: '--configuration $(BuildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: Publish
#   inputs:
#     command: publish
#     projects: '/src/API/API.csproj'
#     publishWebProjects: True
#     zipPublishedProjects: True
#     arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

# - task: PublishBuildArtifacts@1
#   displayName: Publish Artifact
#   inputs:
#     PathtoPublish: '$(build.artifactstagingdirectory)'
